// Generated by shaders/metal/transpile.sh -- do not edit.
// Transpiled from shaders/idwt.comp and shaders/wavelet_dequant.comp.
#pragma once

namespace PyroWave
{
static const char idwt_msl_source[] = R"PYROWAVE_MSL(
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct Registers
{
    int2 resolution;
    float2 inv_resolution;
};

constant bool DCShift_tmp [[function_constant(0)]];
constant bool DCShift = is_function_constant_defined(DCShift_tmp) ? DCShift_tmp : false;

static inline __attribute__((always_inline))
int2 unswizzle8x8(thread const uint& index)
{
    uint y = extract_bits(index, uint(0), uint(1));
    uint x = extract_bits(index, uint(1), uint(2));
    y |= (extract_bits(index, uint(3), uint(2)) << uint(1));
    x |= (extract_bits(index, uint(5), uint(1)) << uint(2));
    return int2(int(x), int(y));
}

static inline __attribute__((always_inline))
bool2 band(thread const bool2& a, thread const bool2& b)
{
    return bool2(a.x && b.x, a.y && b.y);
}

static inline __attribute__((always_inline))
float2 generate_mirror_uv(thread int2& coord, thread const bool& even_x, thread const bool& even_y, constant Registers& _148)
{
    bool2 param = bool2(even_x, even_y);
    bool2 param_1 = coord < int2(0);
    coord -= int2(band(param, param_1));
    coord += int2(1);
    bool2 param_2 = bool2(!even_x, !even_y);
    bool2 param_3 = coord >= _148.resolution;
    coord += int2(band(param_2, param_3));
    float2 uv = float2(coord) * _148.inv_resolution;
    return uv.yx;
}

static inline __attribute__((always_inline))
void store_shared(thread const uint& y, thread const uint& x, thread const float2& v, threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block)
{
    shared_block[y][x] = v;
}

static inline __attribute__((always_inline))
void write_shared_4x4(thread const int2& coord, thread const float4& texels0, thread const float4& texels1, thread const float4& texels2, thread const float4& texels3, threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block)
{
    uint param = uint(coord.y + 0);
    uint param_1 = uint((2 * coord.x) + 0);
    float2 param_2 = float2(texels0.x, texels2.x);
    store_shared(param, param_1, param_2, shared_block);
    uint param_3 = uint(coord.y + 0);
    uint param_4 = uint((2 * coord.x) + 1);
    float2 param_5 = float2(texels1.x, texels3.x);
    store_shared(param_3, param_4, param_5, shared_block);
    uint param_6 = uint(coord.y + 0);
    uint param_7 = uint((2 * coord.x) + 2);
    float2 param_8 = float2(texels0.y, texels2.y);
    store_shared(param_6, param_7, param_8, shared_block);
    uint param_9 = uint(coord.y + 0);
    uint param_10 = uint((2 * coord.x) + 3);
    float2 param_11 = float2(texels1.y, texels3.y);
    store_shared(param_9, param_10, param_11, shared_block);
    uint param_12 = uint(coord.y + 1);
    uint param_13 = uint((2 * coord.x) + 0);
    float2 param_14 = float2(texels0.z, texels2.z);
    store_shared(param_12, param_13, param_14, shared_block);
    uint param_15 = uint(coord.y + 1);
    uint param_16 = uint((2 * coord.x) + 1);
    float2 param_17 = float2(texels1.z, texels3.z);
    store_shared(param_15, param_16, param_17, shared_block);
    uint param_18 = uint(coord.y + 1);
    uint param_19 = uint((2 * coord.x) + 2);
    float2 param_20 = float2(texels0.w, texels2.w);
    store_shared(param_18, param_19, param_20, shared_block);
    uint param_21 = uint(coord.y + 1);
    uint param_22 = uint((2 * coord.x) + 3);
    float2 param_23 = float2(texels1.w, texels3.w);
    store_shared(param_21, param_22, param_23, shared_block);
}

static inline __attribute__((always_inline))
void load_image_with_apron(threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block, constant Registers& _148, thread uint3& gl_WorkGroupID, thread uint& local_index, texture2d_array<float> uTexture, sampler uTextureSmplr)
{
    int2 base_coord = (int2(gl_WorkGroupID.xy) * int2(16)) - int2(2);
    uint param = local_index;
    int2 local_coord0 = int2(2) * unswizzle8x8(param);
    int2 coord0 = base_coord + local_coord0;
    int2 param_1 = coord0;
    bool param_2 = true;
    bool param_3 = true;
    float2 _353 = generate_mirror_uv(param_1, param_2, param_3, _148);
    float3 _358 = float3(_353, 0.0);
    float4 texels0 = uTexture.gather(uTextureSmplr, _358.xy, uint(rint(_358.z)), int2(0), component::x).wxzy;
    int2 param_4 = coord0;
    bool param_5 = false;
    bool param_6 = true;
    float2 _368 = generate_mirror_uv(param_4, param_5, param_6, _148);
    float3 _372 = float3(_368, 2.0);
    float4 texels1 = uTexture.gather(uTextureSmplr, _372.xy, uint(rint(_372.z)), int2(0), component::x).wxzy;
    int2 param_7 = coord0;
    bool param_8 = true;
    bool param_9 = false;
    float2 _381 = generate_mirror_uv(param_7, param_8, param_9, _148);
    float3 _385 = float3(_381, 1.0);
    float4 texels2 = uTexture.gather(uTextureSmplr, _385.xy, uint(rint(_385.z)), int2(0), component::x).wxzy;
    int2 param_10 = coord0;
    bool param_11 = false;
    bool param_12 = false;
    float2 _394 = generate_mirror_uv(param_10, param_11, param_12, _148);
    float3 _398 = float3(_394, 3.0);
    float4 texels3 = uTexture.gather(uTextureSmplr, _398.xy, uint(rint(_398.z)), int2(0), component::x).wxzy;
    int2 param_13 = local_coord0;
    float4 param_14 = texels0;
    float4 param_15 = texels1;
    float4 param_16 = texels2;
    float4 param_17 = texels3;
    write_shared_4x4(param_13, param_14, param_15, param_16, param_17, shared_block);
    int2 local_coord_horiz = int2(int(16u + (2u * (local_index % 2u))), int(2u * (local_index / 2u)));
    if (local_coord_horiz.y < 20)
    {
        int2 param_18 = base_coord + local_coord_horiz;
        bool param_19 = true;
        bool param_20 = true;
        float2 _437 = generate_mirror_uv(param_18, param_19, param_20, _148);
        float3 _440 = float3(_437, 0.0);
        texels0 = uTexture.gather(uTextureSmplr, _440.xy, uint(rint(_440.z)), int2(0), component::x).wxzy;
        int2 param_21 = base_coord + local_coord_horiz;
        bool param_22 = false;
        bool param_23 = true;
        float2 _450 = generate_mirror_uv(param_21, param_22, param_23, _148);
        float3 _453 = float3(_450, 2.0);
        texels1 = uTexture.gather(uTextureSmplr, _453.xy, uint(rint(_453.z)), int2(0), component::x).wxzy;
        int2 param_24 = base_coord + local_coord_horiz;
        bool param_25 = true;
        bool param_26 = false;
        float2 _463 = generate_mirror_uv(param_24, param_25, param_26, _148);
        float3 _466 = float3(_463, 1.0);
        texels2 = uTexture.gather(uTextureSmplr, _466.xy, uint(rint(_466.z)), int2(0), component::x).wxzy;
        int2 param_27 = base_coord + local_coord_horiz;
        bool param_28 = false;
        bool param_29 = false;
        float2 _476 = generate_mirror_uv(param_27, param_28, param_29, _148);
        float3 _479 = float3(_476, 3.0);
        texels3 = uTexture.gather(uTextureSmplr, _479.xy, uint(rint(_479.z)), int2(0), component::x).wxzy;
        int2 param_30 = local_coord_horiz;
        float4 param_31 = texels0;
        float4 param_32 = texels1;
        float4 param_33 = texels2;
        float4 param_34 = texels3;
        write_shared_4x4(param_30, param_31, param_32, param_33, param_34, shared_block);
    }
    int2 local_coord_vert = local_coord_horiz.yx;
    if (local_coord_vert.x < 16)
    {
        int2 param_35 = base_coord + local_coord_vert;
        bool param_36 = true;
        bool param_37 = true;
        float2 _508 = generate_mirror_uv(param_35, param_36, param_37, _148);
        float3 _511 = float3(_508, 0.0);
        texels0 = uTexture.gather(uTextureSmplr, _511.xy, uint(rint(_511.z)), int2(0), component::x).wxzy;
        int2 param_38 = base_coord + local_coord_vert;
        bool param_39 = false;
        bool param_40 = true;
        float2 _521 = generate_mirror_uv(param_38, param_39, param_40, _148);
        float3 _524 = float3(_521, 2.0);
        texels1 = uTexture.gather(uTextureSmplr, _524.xy, uint(rint(_524.z)), int2(0), component::x).wxzy;
        int2 param_41 = base_coord + local_coord_vert;
        bool param_42 = true;
        bool param_43 = false;
        float2 _534 = generate_mirror_uv(param_41, param_42, param_43, _148);
        float3 _537 = float3(_534, 1.0);
        texels2 = uTexture.gather(uTextureSmplr, _537.xy, uint(rint(_537.z)), int2(0), component::x).wxzy;
        int2 param_44 = base_coord + local_coord_vert;
        bool param_45 = false;
        bool param_46 = false;
        float2 _547 = generate_mirror_uv(param_44, param_45, param_46, _148);
        float3 _550 = float3(_547, 3.0);
        texels3 = uTexture.gather(uTextureSmplr, _550.xy, uint(rint(_550.z)), int2(0), component::x).wxzy;
        int2 param_47 = local_coord_vert;
        float4 param_48 = texels0;
        float4 param_49 = texels1;
        float4 param_50 = texels2;
        float4 param_51 = texels3;
        write_shared_4x4(param_47, param_48, param_49, param_50, param_51, shared_block);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
}

static inline __attribute__((always_inline))
float2 load_shared(thread const uint& y, thread const uint& x, threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block)
{
    return shared_block[y][x];
}

static inline __attribute__((always_inline))
void inverse_transform8x2(threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block, thread uint& local_index)
{
    int2 local_coord = int2(int(8u * (local_index % 4u)), int(local_index / 4u));
    spvUnsafeArray<float2, 16> values;
    for (int i = 0; i < 16; i += 2)
    {
        uint param = uint(local_coord.y);
        uint param_1 = uint((local_coord.x + i) + 0);
        float2 v0 = load_shared(param, param_1, shared_block);
        uint param_2 = uint(local_coord.y);
        uint param_3 = uint((local_coord.x + i) + 1);
        float2 v1 = load_shared(param_2, param_3, shared_block);
        values[i + 0] = v0 * 1.23017406463623046875;
        values[i + 1] = v1 * 0.812893092632293701171875;
    }
    for (int i_1 = 2; i_1 < 15; i_1 += 2)
    {
        values[i_1] -= ((values[i_1 - 1] + values[i_1 + 1]) * 0.4435068666934967041015625);
    }
    for (int i_2 = 3; i_2 < 14; i_2 += 2)
    {
        values[i_2] -= ((values[i_2 - 1] + values[i_2 + 1]) * 0.88291108608245849609375);
    }
    for (int i_3 = 4; i_3 < 13; i_3 += 2)
    {
        values[i_3] -= ((values[i_3 - 1] + values[i_3 + 1]) * (-0.052980117499828338623046875));
    }
    for (int i_4 = 5; i_4 < 12; i_4 += 2)
    {
        values[i_4] -= ((values[i_4 - 1] + values[i_4 + 1]) * (-1.58613431453704833984375));
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (int i_5 = 2; i_5 < 6; i_5++)
    {
        float2 a = values[(2 * i_5) + 0];
        float2 b = values[(2 * i_5) + 1];
        float2 t0 = float2(a.x, b.x);
        float2 t1 = float2(a.y, b.y);
        int y_coord = (local_coord.x >> 1) + (i_5 - 2);
        uint param_4 = uint(y_coord);
        uint param_5 = uint((2 * local_coord.y) + 0);
        float2 param_6 = t0;
        store_shared(param_4, param_5, param_6, shared_block);
        uint param_7 = uint(y_coord);
        uint param_8 = uint((2 * local_coord.y) + 1);
        float2 param_9 = t1;
        store_shared(param_7, param_8, param_9, shared_block);
    }
}

static inline __attribute__((always_inline))
void inverse_transform4x2(thread const bool& active_lane, thread const int& y_offset, threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20>& shared_block, thread uint& local_index)
{
    int2 local_coord = int2(int(4u * (local_index % 8u)), int((local_index / 8u) + uint(y_offset)));
    spvUnsafeArray<float2, 12> values;
    if (active_lane)
    {
        for (int i = 0; i < 12; i += 2)
        {
            uint param = uint(local_coord.y);
            uint param_1 = uint((local_coord.x + i) + 0);
            float2 v0 = load_shared(param, param_1, shared_block);
            uint param_2 = uint(local_coord.y);
            uint param_3 = uint((local_coord.x + i) + 1);
            float2 v1 = load_shared(param_2, param_3, shared_block);
            values[i + 0] = v0 * 1.23017406463623046875;
            values[i + 1] = v1 * 0.812893092632293701171875;
        }
        for (int i_1 = 2; i_1 < 11; i_1 += 2)
        {
            values[i_1] -= ((values[i_1 - 1] + values[i_1 + 1]) * 0.4435068666934967041015625);
        }
        for (int i_2 = 3; i_2 < 10; i_2 += 2)
        {
            values[i_2] -= ((values[i_2 - 1] + values[i_2 + 1]) * 0.88291108608245849609375);
        }
        for (int i_3 = 4; i_3 < 9; i_3 += 2)
        {
            values[i_3] -= ((values[i_3 - 1] + values[i_3 + 1]) * (-0.052980117499828338623046875));
        }
        for (int i_4 = 5; i_4 < 8; i_4 += 2)
        {
            values[i_4] -= ((values[i_4 - 1] + values[i_4 + 1]) * (-1.58613431453704833984375));
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (active_lane)
    {
        for (int i_5 = 2; i_5 < 4; i_5++)
        {
            float2 a = values[(2 * i_5) + 0];
            float2 b = values[(2 * i_5) + 1];
            float2 t0 = float2(a.x, b.x);
            float2 t1 = float2(a.y, b.y);
            int y_coord = (local_coord.x >> 1) + (i_5 - 2);
            uint param_4 = uint(y_coord);
            uint param_5 = uint((2 * local_coord.y) + 0);
            float2 param_6 = t0;
            store_shared(param_4, param_5, param_6, shared_block);
            uint param_7 = uint(y_coord);
            uint param_8 = uint((2 * local_coord.y) + 1);
            float2 param_9 = t1;
            store_shared(param_7, param_8, param_9, shared_block);
        }
    }
}

kernel void pyrowave_idwt(constant Registers& _148 [[buffer(0)]], texture2d_array<float> uTexture [[texture(0)]], texture2d<float, access::write> uOutput [[texture(1)]], sampler uTextureSmplr [[sampler(0)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]])
{
    threadgroup spvUnsafeArray<spvUnsafeArray<float2, 41>, 20> shared_block;
    uint local_index = gl_LocalInvocationIndex;
    load_image_with_apron(shared_block, _148, gl_WorkGroupID, local_index, uTexture, uTextureSmplr);
    inverse_transform8x2(shared_block, local_index);
    bool param = local_index < 32u;
    int param_1 = 16;
    inverse_transform4x2(param, param_1, shared_block, local_index);
    threadgroup_barrier(mem_flags::mem_threadgroup);
    inverse_transform8x2(shared_block, local_index);
    threadgroup_barrier(mem_flags::mem_threadgroup);
    uint param_2 = local_index;
    int2 local_coord = unswizzle8x8(param_2);
    for (int y = local_coord.y; y < 16; y += 8)
    {
        for (int x = local_coord.x; x < 32; x += 8)
        {
            uint param_3 = uint(y);
            uint param_4 = uint(x);
            float2 v = load_shared(param_3, param_4, shared_block);
            if (DCShift)
            {
                v += float2(0.5);
            }
            uOutput.write(v.xxxx, uint2((int2((2 * y) + 0, x) + (int2(32) * int2(gl_WorkGroupID.yx)))));
            uOutput.write(v.yyyy, uint2((int2((2 * y) + 1, x) + (int2(32) * int2(gl_WorkGroupID.yx)))));
        }
    }
}

)PYROWAVE_MSL";

static const char wavelet_dequant_msl_source[] = R"PYROWAVE_MSL(
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

template<typename T>
inline T spvSubgroupShuffleUp(T value, ushort delta)
{
    return simd_shuffle_up(value, delta);
}

template<>
inline bool spvSubgroupShuffleUp(bool value, ushort delta)
{
    return !!simd_shuffle_up((ushort)value, delta);
}

template<uint N>
inline vec<bool, N> spvSubgroupShuffleUp(vec<bool, N> value, ushort delta)
{
    return (vec<bool, N>)simd_shuffle_up((vec<ushort, N>)value, delta);
}

struct Payloads8
{
    uchar data[1];
};

struct Registers
{
    int2 resolution;
    int output_layer;
    int block_offset_32x32;
    int block_stride_32x32;
};

struct PayloadOffsets
{
    uint data[1];
};

struct Payloads
{
    uint data[1];
};

struct Payloads16
{
    ushort data[1];
};

constant spvUnsafeArray<int, 8> _143 = spvUnsafeArray<int, 8>({ 0, 0, 0, 0, 0, 0, 0, 0 });

static inline __attribute__((always_inline))
int2 unswizzle8x8(thread const uint& index)
{
    uint y = extract_bits(index, uint(0), uint(1));
    uint x = extract_bits(index, uint(1), uint(2));
    y |= (extract_bits(index, uint(3), uint(2)) << uint(1));
    x |= (extract_bits(index, uint(5), uint(1)) << uint(2));
    return int2(int(x), int(y));
}

static inline __attribute__((always_inline))
float2x4 decode_payload(thread const uint& code_word, thread const uint& q_bits, thread const uint& offset, thread const uint& block_index, const device Payloads8& payload_data_u8)
{
    bool empty_block = code_word == 0u;
    if (empty_block)
    {
        return float2x4(float4(0.0), float4(0.0));
    }
    int bit_offset = 2 * int(block_index);
    uint lsbs = code_word & 21845u;
    uint msbs = code_word & 43690u;
    uint msbs_shift = msbs >> uint(1);
    msbs |= msbs_shift;
    uint byte_offset = (uint(int(popcount(extract_bits(lsbs, uint(0), uint(bit_offset)))) + int(popcount(extract_bits(msbs, uint(0), uint(bit_offset))))) + (q_bits * block_index)) + offset;
    uint payload = uint(payload_data_u8.data[byte_offset]);
    uint local_control_word = extract_bits(code_word, uint(bit_offset), uint(2));
    spvUnsafeArray<int, 8> decoded_abs = spvUnsafeArray<int, 8>({ 0, 0, 0, 0, 0, 0, 0, 0 });
    int plane_iterations = int(q_bits + local_control_word);
    int _151 = plane_iterations - 1;
    for (int q = _151; q >= 0; q--)
    {
        for (int b = 0; b < 8; b++)
        {
            int decoded = int(extract_bits(payload, uint(b), uint(1)));
            decoded_abs[b] = insert_bits(decoded_abs[b], decoded, uint(q), uint(1));
        }
        byte_offset++;
        payload = uint(payload_data_u8.data[byte_offset]);
    }
    float2x4 m;
    for (int i = 0; i < 4; i++)
    {
        for (int j = 0; j < 2; j++)
        {
            float v = float(decoded_abs[(i * 2) + j]);
            if (v != 0.0)
            {
                v += 0.5;
            }
            m[j][i] = v;
        }
    }
    return m;
}

static inline __attribute__((always_inline))
float decode_quant(thread const uint& quant_code)
{
    int e = 4 - int(quant_code >> uint(3));
    int m = int(quant_code) & 7;
    float inv_quant = 1.1920928955078125e-07 * float((8 + m) * (1 << (20 + e)));
    return inv_quant;
}

static inline __attribute__((always_inline))
float decode_quant_scale(thread const uint& code)
{
    return (float(code) / 8.0) + 0.25;
}

static inline __attribute__((always_inline))
uint scan_subgroups(thread uint& v, thread uint& gl_NumSubgroups, thread uint& gl_SubgroupInvocationID)
{
    for (uint i = 1u; i < gl_NumSubgroups; i *= 2u)
    {
        uint up = spvSubgroupShuffleUp(v, i);
        v += ((gl_SubgroupInvocationID >= i) ? up : 0u);
    }
    return v;
}

static inline __attribute__((always_inline))
void scan_subgroups_fallback(thread const uint& local_index, thread uint& gl_NumSubgroups, threadgroup spvUnsafeArray<uint, 32>& shared_sign_scan)
{
    threadgroup_barrier(mem_flags::mem_threadgroup);
    bool active_lane = local_index < gl_NumSubgroups;
    uint v = 0u;
    if (active_lane)
    {
        v = shared_sign_scan[local_index];
    }
    for (uint i = 1u; i < gl_NumSubgroups; i *= 2u)
    {
        uint up = 0u;
        bool do_work = (local_index >= i) && active_lane;
        if (do_work)
        {
            up = shared_sign_scan[local_index - i];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (do_work)
        {
            v += up;
            shared_sign_scan[local_index] = v;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
}

kernel void pyrowave_wavelet_dequant(const device void* spvBufferAliasSet0Binding2 [[buffer(0)]], constant Registers& registers [[buffer(1)]], const device PayloadOffsets& payload_offsets [[buffer(2)]], texture2d_array<float, access::write> uDequantImg [[texture(0)]], uint gl_NumSubgroups [[simdgroups_per_threadgroup]], uint gl_SubgroupInvocationID [[thread_index_in_simdgroup]], uint gl_SubgroupID [[simdgroup_index_in_threadgroup]], uint gl_SubgroupSize [[threads_per_simdgroup]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]])
{
    const device auto& payload_data_u8 = *(const device Payloads8*)spvBufferAliasSet0Binding2;
    const device auto& payload_data_u32 = *(const device Payloads*)spvBufferAliasSet0Binding2;
    const device auto& payload_data_u16 = *(const device Payloads16*)spvBufferAliasSet0Binding2;
    threadgroup spvUnsafeArray<uint, 32> shared_sign_scan;
    threadgroup uint shared_sign_offset;
    threadgroup spvUnsafeArray<uint, 16> shared_plane_byte_offsets;
    uint local_index = (gl_SubgroupID * gl_SubgroupSize) + gl_SubgroupInvocationID;
    int block_index_32x32 = int((uint(registers.block_offset_32x32) + (gl_WorkGroupID.y * uint(registers.block_stride_32x32))) + gl_WorkGroupID.x);
    uint block_local_index = extract_bits(local_index, uint(0), uint(3));
    uint block_x = extract_bits(local_index, uint(3), uint(2));
    uint block_y = extract_bits(local_index, uint(5), uint(2));
    uint linear_block = (block_y * 4u) + block_x;
    uint param = block_local_index << uint(3);
    int2 local_coord = unswizzle8x8(param);
    int2 coord = int2(gl_WorkGroupID.xy) * int2(32);
    coord += (int2(8) * int2(int(block_x), int(block_y)));
    coord += local_coord;
    uint offset_u32 = payload_offsets.data[block_index_32x32];
    if (offset_u32 == 4294967295u)
    {
        for (int j = 0; j < 2; j++)
        {
            for (int i = 0; i < 4; i++)
            {
                int3 _459 = int3(coord + int2(i, j), registers.output_layer);
                uDequantImg.write(float4(0.0), uint2(_459.xy), uint(_459.z));
            }
        }
        return;
    }
    uint ballot = payload_data_u32.data[offset_u32] & 65535u;
    uint q_code = payload_data_u32.data[offset_u32 + 1u] & 255u;
    if (local_index < 16u)
    {
        uint control_word = 0u;
        uint q_bits = 0u;
        if (extract_bits(ballot, uint(int(local_index)), uint(1)) != 0u)
        {
            uint local_code_offset = uint(int(popcount(extract_bits(ballot, uint(0), uint(int(local_index))))));
            control_word = uint(payload_data_u16.data[((offset_u32 * 2u) + 4u) + local_code_offset]);
            q_bits = uint(payload_data_u8.data[(((offset_u32 * 4u) + 8u) + uint(int(popcount(ballot)) * 2)) + local_code_offset]) & 15u;
        }
        uint lsbs = control_word & 21845u;
        uint msbs = control_word & 43690u;
        uint msbs_shift = msbs >> uint(1);
        msbs |= msbs_shift;
        uint byte_cost = uint(int(popcount(lsbs)) + int(popcount(msbs))) + (q_bits * 8u);
        uint byte_scan = (((offset_u32 * 4u) + 8u) + uint(3 * int(popcount(ballot)))) + simd_prefix_inclusive_sum(byte_cost);
        if (local_index == 15u)
        {
            shared_sign_offset = 8u * byte_scan;
        }
        shared_plane_byte_offsets[local_index] = byte_scan - byte_cost;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float2x4 v;
    int significant_count;
    if (extract_bits(ballot, uint(int(linear_block)), uint(1)) != 0u)
    {
        uint local_code_offset_1 = uint(int(popcount(extract_bits(ballot, uint(0), uint(int(linear_block))))));
        uint control_word_1 = uint(payload_data_u16.data[((offset_u32 * 2u) + 4u) + local_code_offset_1]);
        uint control_word2 = uint(payload_data_u8.data[(((offset_u32 * 4u) + 8u) + uint(int(popcount(ballot)) * 2)) + local_code_offset_1]);
        uint param_1 = control_word_1;
        uint param_2 = control_word2 & 15u;
        uint param_3 = shared_plane_byte_offsets[linear_block];
        uint param_4 = block_local_index;
        v = decode_payload(param_1, param_2, param_3, param_4, payload_data_u8);
        significant_count = 0;
        for (int j_1 = 0; j_1 < 2; j_1++)
        {
            for (int i_1 = 0; i_1 < 4; i_1++)
            {
                significant_count += int(v[j_1][i_1] != 0.0);
            }
        }
        uint param_5 = q_code;
        float q = decode_quant(param_5);
        uint param_6 = extract_bits(control_word2, uint(4), uint(4));
        float inv_scale = q * decode_quant_scale(param_6);
        v = v * inv_scale;
    }
    else
    {
        v = float2x4(float4(0.0), float4(0.0));
        significant_count = 0;
    }
    int significant_scan = simd_prefix_inclusive_sum(significant_count);
    if (gl_SubgroupInvocationID == (gl_SubgroupSize - 1u))
    {
        shared_sign_scan[gl_SubgroupID] = uint(significant_scan);
    }
    if (gl_NumSubgroups <= 8u)
    {
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (gl_SubgroupSize <= 32u)
        {
            if (local_index < gl_NumSubgroups)
            {
                shared_sign_scan[local_index] = simd_prefix_inclusive_sum(shared_sign_scan[local_index]);
            }
        }
        else
        {
            if (local_index < gl_NumSubgroups)
            {
                uint param_7 = shared_sign_scan[local_index];
                uint _718 = scan_subgroups(param_7, gl_NumSubgroups, gl_SubgroupInvocationID);
                shared_sign_scan[local_index] = _718;
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    else
    {
        uint param_8 = local_index;
        scan_subgroups_fallback(param_8, gl_NumSubgroups, shared_sign_scan);
    }
    uint sign_offset = (shared_sign_offset + uint(significant_scan)) - uint(significant_count);
    if (gl_SubgroupID != 0u)
    {
        sign_offset += shared_sign_scan[gl_SubgroupID - 1u];
    }
    uint sign_word = payload_data_u32.data[(sign_offset / 32u) + 0u];
    uint sign_word_upper = payload_data_u32.data[(sign_offset / 32u) + 1u];
    uint masked_sign_offset = sign_offset & 31u;
    if (masked_sign_offset != 0u)
    {
        sign_word = sign_word >> masked_sign_offset;
        sign_word |= (sign_word_upper << (32u - masked_sign_offset));
    }
    int sign_counter = 0;
    for (int i_2 = 0; i_2 < 4; i_2++)
    {
        for (int j_2 = 0; j_2 < 2; j_2++)
        {
            if (v[j_2][i_2] != 0.0)
            {
                v[j_2][i_2] *= (1.0 - (2.0 * float(extract_bits(sign_word, uint(sign_counter), uint(1)))));
                sign_counter++;
            }
        }
    }
    for (int j_3 = 0; j_3 < 2; j_3++)
    {
        for (int i_3 = 0; i_3 < 4; i_3++)
        {
            int3 _841 = int3(coord + int2(i_3, j_3), registers.output_layer);
            uDequantImg.write(float4(v[j_3][i_3]), uint2(_841.xy), uint(_841.z));
        }
    }
}

)PYROWAVE_MSL";
}
