#!/bin/bash

# Regenerates the Metal shaders for the decode path from the GLSL sources.
#
# Requires glslang and spirv-cross (brew install glslang spirv-cross).
# Only the two shaders the Metal decoder needs are transpiled; the encoder,
# the fragment iDWT path and rate control stay Vulkan only.
#
# Run from the repository root:  ./shaders/metal/transpile.sh

set -e

cd "$(dirname "$0")/../.."

OUT=shaders/metal
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# slangmosh injects this; a bare glslangValidator invocation has to ask for it
# explicitly or the #includes in the shaders are rejected.
PREAMBLE='#extension GL_GOOGLE_include_directive : require'

# PRECISION=2 is FP32; PRECISION=0 with FP16 is the half precision path, which
# uses an R16F wavelet pyramid and halves the iDWT's threadgroup array.
# STORAGE_MODE=0 is the plain SSBO path with 8/16-bit storage.
glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=2 -DFP16=0 -Ishaders \
	-o "$TMP/idwt.spv" shaders/idwt.comp

glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=1 -DFP16=1 -Ishaders \
	-o "$TMP/idwt_fp16_storage.spv" shaders/idwt.comp

glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=0 -DFP16=1 -Ishaders \
	-o "$TMP/idwt_fp16.spv" shaders/idwt.comp

glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DSTORAGE_MODE=0 -Ishaders \
	-o "$TMP/wavelet_dequant.spv" shaders/wavelet_dequant.comp

# Encoder. dwt mirrors idwt's three precision variants; the rest are invariant.
glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=2 -DFP16=0 -Ishaders -o "$TMP/dwt.spv" shaders/dwt.comp
glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=1 -DFP16=1 -Ishaders -o "$TMP/dwt_fp16_storage.spv" shaders/dwt.comp
glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" \
	-DPRECISION=0 -DFP16=1 -Ishaders -o "$TMP/dwt_fp16.spv" shaders/dwt.comp

for enc_shader in wavelet_quant analyze_rate_control analyze_rate_control_finalize \
	resolve_rate_control block_packing; do
	glslangValidator --target-env vulkan1.3 -P"$PREAMBLE" -Ishaders \
		-o "$TMP/$enc_shader.spv" "shaders/$enc_shader.comp"
done

# Both modules declare main(), so rename them to get useful names in Metal GPU
# captures. Note the two sources still cannot be concatenated: SPIRV-Cross emits
# its own copy of spvUnsafeArray and a differently shaped Registers struct into
# each, so they are compiled as two separate MTLLibrary objects.
spirv-cross --msl --msl-version 30000 \
	--rename-entry-point main pyrowave_idwt comp \
	"$TMP/idwt.spv" --output "$OUT/idwt.metal"

spirv-cross --msl --msl-version 30000 \
	--rename-entry-point main pyrowave_idwt comp \
	"$TMP/idwt_fp16_storage.spv" --output "$OUT/idwt_fp16_storage.metal"

spirv-cross --msl --msl-version 30000 \
	--rename-entry-point main pyrowave_idwt comp \
	"$TMP/idwt_fp16.spv" --output "$OUT/idwt_fp16.metal"

spirv-cross --msl --msl-version 30000 \
	--rename-entry-point main pyrowave_wavelet_dequant comp \
	"$TMP/wavelet_dequant.spv" --output "$OUT/wavelet_dequant.metal"

for enc_shader in dwt dwt_fp16_storage dwt_fp16; do
	spirv-cross --msl --msl-version 30000 \
		--rename-entry-point main pyrowave_dwt comp \
		"$TMP/$enc_shader.spv" --output "$OUT/$enc_shader.metal"
done

for enc_shader in wavelet_quant analyze_rate_control analyze_rate_control_finalize \
	resolve_rate_control block_packing; do
	spirv-cross --msl --msl-version 30000 \
		--rename-entry-point main "pyrowave_$enc_shader" comp \
		"$TMP/$enc_shader.spv" --output "$OUT/$enc_shader.metal"
done

# The decoder compiles the MSL at runtime, so embed both sources as string
# literals rather than shipping a separate .metallib.
EMBED=$OUT/pyrowave_msl.h
{
	echo "// Generated by shaders/metal/transpile.sh -- do not edit."
	echo "// Transpiled from shaders/idwt.comp and shaders/wavelet_dequant.comp."
	echo "#pragma once"
	echo
	echo "namespace PyroWave"
	echo "{"
	echo "static const char idwt_msl_source[] = R\"PYROWAVE_MSL("
	cat "$OUT/idwt.metal"
	echo ")PYROWAVE_MSL\";"
	echo
	echo "static const char idwt_fp16_storage_msl_source[] = R\"PYROWAVE_MSL("
	cat "$OUT/idwt_fp16_storage.metal"
	echo ")PYROWAVE_MSL\";"
	echo
	echo "static const char idwt_fp16_msl_source[] = R\"PYROWAVE_MSL("
	cat "$OUT/idwt_fp16.metal"
	echo ")PYROWAVE_MSL\";"
	echo
	echo "static const char wavelet_dequant_msl_source[] = R\"PYROWAVE_MSL("
	cat "$OUT/wavelet_dequant.metal"
	echo ")PYROWAVE_MSL\";"
	for enc_shader in dwt dwt_fp16_storage dwt_fp16 wavelet_quant analyze_rate_control \
		analyze_rate_control_finalize resolve_rate_control block_packing; do
		echo
		echo "static const char ${enc_shader}_msl_source[] = R\"PYROWAVE_MSL("
		cat "$OUT/$enc_shader.metal"
		echo ")PYROWAVE_MSL\";"
	done
	echo "}"
} > "$EMBED"

echo "Wrote decode + encode MSL into $OUT and $EMBED"
